/*
 * Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
 *
 * This software is the property of WSO2 LLC. and its suppliers, if any.
 * Dissemination of any information or reproduction of any material contained
 * herein is strictly forbidden, unless permitted by WSO2 in accordance with
 * the WSO2 Commercial License available at http://wso2.com/licenses.
 * For specific language governing the permissions and limitations under
 * this license, please see the license as well as any agreement you’ve
 * entered into with WSO2 governing the purchase of this software and any
 * associated services.
 */
window.__RUNTIME_CONFIG__ = {
  API_BALLERINA_CENTRAL_URL: 'https://api.central.ballerina.io/2.0',
  API_BASE_URL: 'https://app.choreo.dev',
  MOESIF_API_BASE_URL: 'https://apis.choreo.dev/moesif-key/0.1.0',
  MOESIF_SETTINGS_PAGE_ENABLED: 'true',
  PROJECT_API_BASE_URL: 'https://apis.choreo.dev/projects/1.0.0/graphql',
  DECLARATIVE_API_BASE_URL: 'https://apis.choreo.dev/declarative-api/v1.0',
  AI_COPILOT_URL_SUFFIX: '/systemapis/aicopilot/v1.0/copilot',
  AI_COPILOT_BLOG_URL: 'https://wso2.com/library/blogs/introducing-choreo-copilot/',
  CIO_DASHBOARD_QUERY_API_URL: 'https://apis.choreo.dev/cio-query-api/1.0.0/query',
  CIO_CONFIGURATOR_API_URL: 'https://apis.choreo.dev/cio-incident-configurator/1.0.0',
  DEVOPS_API_BASE_URL: 'https://apis.choreo.dev/devops/1.0.0',
  CONFIG_MAPPING_SERVICE_URL: 'https://apis.choreo.dev/config-mapping-svc/v1.0',
  PLATFORM_SERVICES_API_BASE_URL: 'https://apis.choreo.dev/platform-services/v1.0',
  WORKFLOW_MGT_API_URL: 'https://apis.choreo.dev/workflow-mgt/v1.0',
  CHOREO_APP_SERVICE_BASE_URL: 'https://app.choreo.dev',
  SUBSCRIPTION_API_URL: 'https://subscriptions.wso2.com/api',
  ORG_MANAGEMENT_API_URL: 'https://apis.choreo.dev/org-mgt/1.0.0/orgs',
  ORG_MANAGEMENT_API_URL_V2: 'https://apis.choreo.dev/org-mgt/1.0.0',
  AUDIT_LOGGING_API_URL: 'https://apis.choreo.dev/audit-logging/1.0.0/orgs',
  COMPONENT_CREATION_STATUS_API_URL:
    'https://apis.choreo.dev/component-creation',
  COMPONENT_MANAGEMENT_API_URL: 'https://apis.choreo.dev/component-mgt/1.0.0/orgs',
  CONFIG_MANAGEMENT_API_URL: 'https://apis.choreo.dev/config-mgt/1.0.0/orgs',
  CONFIG_GROUP_MANAGEMENT_API_URL: 'https://apis.choreo.dev/config-svc/v1.0/configs/groups',
  COMPONENT_UTILS_API_URL: 'https://apis.choreo.dev/component-utils/1.0.0',
  ON_PREM_KEY_API_URL: 'https://apis.choreo.dev/onprem-key-mgt/1.0.0/orgs',
  USERS_MANAGEMENT_API_URL: 'https://apis.choreo.dev/user-mgt/1.0.0',
  BUILT_IN_IDP_USER_MGT_BASE_URL: 'https://apis.choreo.dev',
  APPDEV_AUTHZ_BASE_URL: 'https://apis.choreo.dev',
  ORGANIZATION_API_URL: 'https://apis.choreo.dev/orgs/1.0.0',
  CDN_THEME_URL: 'https://choreoproddevportalcdn36.blob.core.windows.net',
  API_MANAGER_BASE_URL: 'https://sts.choreo.dev',
  CRYPTO_KEY_SERVICE_BASE_URL: 'https://apis.choreo.dev/crypto-key-service/0.1.0',
  WEB_SUB_HUB_URL: 'https://hub.websubhub.choreo.dev/hub',
  APIM_DCR_VERSION: 'v0.17',
  APIM_DCR_GRANT_TYPE: 'client_credentials',
  API_DEVPORTAL_URL: 'https://devportal.choreo.dev',
  API_DEVOPSPORTAL_URL: 'https://devops.choreo.dev',
  API_GATEWAY_ENDPOINT_SUFFIX: 'choreoapis.dev',
  APIM_PUBLISHER_ENDPOINT_PREFIX: '/api/am/publisher/v2/',
  APIM_ADMIN_ENDPOINT_PREFIX: '/api/am/admin/v2/',
  IPIFY_SERVICE_URL: 'https://api.ipify.org/?format=json',
  ENABLE_ADDING_SF_LEAD: 'true',
  GA_TRACKING_CODE: 'UA-206124793-2',
  HOTJAR_ID: '',
  VWO_ACCOUNT_ID: '547890', // DEPRECATED: VWO tag is injected via Google Tag Manager
  TERMS_OF_USE_LINK: 'https://wso2.com/choreo/terms-of-use',
  CHOREO_HOME_PAGE: 'https://wso2.com/choreo/',
  PRIVACY_POLICY_LINK: 'https://wso2.com/choreo/privacy-policy',
  SUPPORT_COMMUNITY_LINK: 'https://discord.com/invite/wso2',
  REQUEST_DEMO_LINK: 'https://wso2.com/choreo/request-demo/',
  SUPPORT_PORTAL_LINK: 'https://cloud-support.wso2.com/wso2_cloud_support',
  CHOREO_SYSTEM_ORG: 'choreosystem',
  INTRO_VIDEO_URL: '',
  HOTJAR_VERSION: '6',
  ASGARDEO_SDK_RESOURCE_SERVER_URLS:
    'https://sts.choreo.dev|https://api.asgardeo.io|https://sts.preview.choreo.dev|https://apim.preview.choreo.dev|https://id.choreo.dev|https://console.preview.choreo.dev|https://console.choreo.dev|https://app.preview.choreo.dev|https://app.choreo.dev|https://choreocontrolplane.choreo.dev|https://choreocontrolplane.preview.choreo.dev|https://api.central.ballerina.io|https://subscriptions.wso2.com|https://apis.choreo.dev/projects/1.0.0/graphql|https://apis.choreo.dev/org-mgt/1.0.0/orgs|https://apis.choreo.dev/org-mgt/1.0.0|https://apis.choreo.dev/moesif-key/0.1.0|https://apis.choreo.dev/component-mgt/1.0.0|https://apis.choreo.dev/user-mgt/1.0.0|https://apis.choreo.dev/orgs/1.0.0|https://apis.choreo.dev/config-mgt/1.0.0/orgs|https://apis.choreo.dev/alert-configuration-service|https://apis.choreo.dev/devops/1.0.0|https://apis.choreo.dev/cio-query-api/1.0.0/query|https://apis.choreo.dev/cio-incident-configurator/1.0.0|https://apis.choreo.dev/crypto-key-service/0.1.0|https://apis.choreo.dev/custom-domain/1.0.0/orgs|https://apis.choreo.dev/onprem-key-mgt/1.0.0/orgs|https://apis.choreo.dev/audit-logging/1.0.0/orgs|https://apis.choreo.dev/component-utils/1.0.0|https://apis.choreo.dev/marketplace/0.1.0|https://choreo-shared-choreo-samples-cdne.azureedge.net|https://apis.choreo.dev/config-svc/v1.0/configs/groups|https://apis.choreo.dev/config-mapping-svc/v1|https://apis.choreo.dev/platform-services/v1.0|https://apis.choreo.dev/connections/v1.0|https://apis.choreo.dev/authz-mgt/v1.0|https://apis.choreo.dev/apim-appdev/v1.0|https://apis.choreo.dev/user-store-mgt/v1.0|https://apis.choreo.dev/code-challenge-eval/v1|https://apis.choreo.dev/component-creation|https://apis.choreo.dev/url-mgt/v1.0|https://apis.choreo.dev/workflow-mgt/v1.0|https://apis.choreo.dev/declarative-api/v1.0|https://apis.choreo.dev/governance/v1.0',
  ASGARDEO_SDK_SCOPES: 'email|profile|groups',
  DEVPORTAL_SCOPES: 'apim:subscribe apim:sub_manage apim:app_manage apim:app_import_export apim:api_key environments:view_prod environments:view_dev urn:choreosystem:customdomainapi:custom_domain_view default',
  ASGARDEO_SESSION_EXTENSION_RESOURCE:
    '/t/a/identity/extend-session',
  ASGARDEO_SESSION_EXTENSION_INTERVAL:
    '28800000',
  ASGARDEO_SDK_CONFIG: {
    endpoints: {
      authorizationEndpoint:
        'https://api.asgardeo.io/t/a/oauth2/authorize',
      tokenEndpoint: 'https://api.asgardeo.io/t/a/oauth2/token',
      endSessionEndpoint: 'https://api.asgardeo.io/t/a/oidc/logout',
    },
    overrideWellEndpointConfig:
      'true',
    signInRedirectURL: 'https://console.choreo.dev/signin',
    signOutRedirectURL: 'https://console.choreo.dev/login',
    clientID: 'aVKhTSUMu_QfEwmCtrcuWoLy92oa',
    baseUrl: 'https://api.asgardeo.io',
    clientHost: 'https://console.choreo.dev',
    enablePKCE: 'true',
    storage: 'sessionStorage',
    checkSessionInterval: '-1',
    disableTrySignInSilently: 'true',
  },
  TOKEN_EXCHANGE_CONFIG: {
    tokenEndpoint: 'https://sts.choreo.dev:443/oauth2/token',
    attachToken: 'false',
    data: {
      client_id: 'ciwnWuwZfbcdzBUcnkhKvi_mcBUa',
      grant_type: 'urn:ietf:params:oauth:grant-type:token-exchange',
      subject_token_type: 'urn:ietf:params:oauth:token-type:jwt',
      requested_token_type: 'urn:ietf:params:oauth:token-type:jwt',
      scope: 'apim:api_manage apim:subscription_manage apim:tier_manage apim:admin apim:publisher_settings environments:view_prod environments:view_dev choreo:user_manage apim:dcr:app_manage choreo:deployment_manage choreo:dev_env_manage choreo:prod_env_manage choreo:non_prod_env_manage choreo:component_manage choreo:project_manage choreo:project_view apim:api_publish apim:document_manage apim:api_settings apim:subscription_view apim:environment_manage apim:subscribe choreo:log_view_non_prod choreo:log_view_prod urn:choreosystem:usermanagement:role_mapping_manage urn:choreosystem:usermanagement:role_mapping_view urn:choreosystem:usermanagement:role_mapping_create urn:choreosystem:usermanagement:role_mapping_update urn:choreosystem:usermanagement:role_mapping_delete urn:choreosystem:configmanagement:global_config_view urn:choreosystem:configmanagement:global_config_create urn:choreosystem:configmanagement:global_config_update urn:choreosystem:configmanagement:global_config_delete urn:choreosystem:configmanagement:global_config_manage urn:choreosystem:configmanagement:config_view urn:choreosystem:configmanagement:config_create urn:choreosystem:configmanagement:config_delete urn:choreosystem:configmanagement:config_manage urn:choreosystem:customdomainapi:custom_domain_view urn:choreosystem:customdomainapi:custom_domain_create urn:choreosystem:customdomainapi:custom_domain_update urn:choreosystem:customdomainapi:custom_domain_delete urn:choreosystem:customdomainapi:custom_domain_manage urn:choreosystem:usermanagement:role_view urn:choreosystem:usermanagement:role_create urn:choreosystem:usermanagement:role_update urn:choreosystem:usermanagement:role_delete urn:choreosystem:usermanagement:role_manage urn:choreosystem:usermanagement:role_manage urn:choreosystem:onpremkeymanagement:on_prem_key_view urn:choreosystem:onpremkeymanagement:on_prem_key_create urn:choreosystem:onpremkeymanagement:on_prem_key_delete urn:choreosystem:onpremkeymanagement:on_prem_key_update urn:choreosystem:onpremkeymanagement:on_prem_key_manage urn:choreosystem:organizationmanagement:theme_view urn:choreosystem:organizationmanagement:theme_create urn:choreosystem:organizationmanagement:theme_delete urn:choreosystem:organizationmanagement:theme_deploy urn:choreosystem:organizationmanagement:theme_manage urn:choreosystem:organizationmanagement:enterprise_login_config_view urn:choreosystem:organizationmanagement:enterprise_login_config_manage urn:choreosystem:organizationmanagement:self_signup_config_view urn:choreosystem:organizationmanagement:self_signup_config_update urn:choreosystem:organizationmanagement:self_signup_manage urn:choreosystem:organizationmanagement:self_signup_approval_view urn:choreosystem:organizationmanagement:self_signup_approval_update urn:choreosystem:usermanagement:user_manage urn:choreosystem:usermanagement:user_view urn:choreosystem:usermanagement:user_delete urn:choreosystem:usermanagement:user_update urn:choreosystem:usermanagement:permission_view urn:choreosystem:usermanagement:invitation_manage urn:choreosystem:usermanagement:invitation_view urn:choreosystem:usermanagement:invitation_send urn:choreosystem:usermanagement:invitation_delete urn:choreosystem:usermanagement:invitation_delete urn:choreosystem:componentsmanagement:component_trigger urn:choreosystem:componentsmanagement:component_create urn:choreosystem:componentsmanagement:component_config_view urn:choreosystem:componentsmanagement:component_logs_view urn:choreosystem:componentsmanagement:component_init_view urn:choreosystem:componentsmanagement:component_file_view urn:choreosystem:componentsmanagement:component_manage urn:choreosystem:choreodevopsportalapi:deployment_manage urn:choreosystem:choreodevopsportalapi:component_manage apim:api_view apim:tier_view apim:api_generate_key urn:choreosystem:choreodevopsportalapi:deployment_view urn:choreosystem:choreoauditloggingapi:audit_logs_view urn:choreosystem:choreoauditloggingapi:audit_logs_manage urn:choreosystem:componentutils:component_manage urn:choreosystem:componentutils:component_file_view urn:choreosystem:componentutils:component_trigger urn:choreosystem:componentutils:component_logs_view urn:choreosystem:organizationapi:org_manage choreo:domain_manage choreo:domain_view choreo:url_mapping_manage choreo:url_mapping_approve choreo:url_mapping_view choreo:insights_org_view',
      subject_token: '{{token}}',
    },
    id: 'apim-token-exchange',
    returnResponse: 'true',
    returnsSession: 'true',
    signInRequired: 'true',
    shouldReplayAfterRefresh: true,
  },
  ORGANIZATION_ENDPOINT: 'https://app.choreo.dev/apim/devportal/organizations',
  FIDP_GOOGLE: 'google',
  FIDP_GITHUB: 'github',
  FIDP_MICROSOFT: 'microsoft',
  FIDP_ANONYMOUS: 'choreoanonymous',
  FIDP_ENTERPRISE: 'EnterpriseIDP',
  FIDP_E2E: 'choreoe2etest',
  AUTHENTICATOR_GOOGLE: 'GoogleOIDCAuthenticator',
  AUTHENTICATOR_GITHUB: 'GithubAuthenticator',
  AUTHENTICATOR_MICROSOFT: '$REACT_APP_AUTHENTICATOR_MICROSOFT',
  AUTHENTICATOR_ANONYMOUS: 'OpenIDConnectAuthenticator',
  AUTHENTICATOR_ENTERPRISE: 'EnterpriseIDPAuthenticator',
  GTM_ID: 'GTM-KJJQ2NQ',
  INSIGHTS_CONFIG: {
    queryAPIUrl: 'https://choreocontrolplane.choreo.dev/93tu/insights/1.0.0/query-api',
    alertAPIUrl: 'https://choreocontrolplane.choreo.dev/93tu/insightsalert/1.0.0/',
    showCustomReports: 'true',
    showGeoMap: 'true',
  },
  GATEWAY_BASE_URL: 'https://choreocontrolplane.choreo.dev/93tu',
  CONSOLE_ORIGIN: 'https://console.choreo.dev',
  ALERT_CONFIG_BASE_URL: 'https://apis.choreo.dev',
  BILLING_CONSOLE_URL: 'https://subscriptions.wso2.com',
  ENABLE_BILLING_FEATURE: 'true',
  CHOREO_STEP_BASED_ENTERPRISE_TIER_UUID:
    '01ec1f84-ce3d-122e-ac9b-f10c95fd72da',
  CHOREO_ENTERPRISE_TIER_UUID: '4abe3757-86f6-47de-994f-f02fb0522e99',
  ENABLE_CONNECTOR_PUBLISH_FEATURE:
    'true',
  ENABLE_APPROVAL_WORKFLOW_FEATURE:
    'false',
  ENABLE_ENTERPRISE_LOGIN_ORGS_FEATURE:
    'true',
  ENABLE_MEDIATION_POLICY_FEATURE: 'false',
  ENABLE_CONNECTOR_DELETE_AND_REPUBLISH_FEATURE:
    'true',
  ALLOW_RBAC: 'true',
  ENABLE_MICROSOFT_LOGIN: 'true',
  ENABLE_GOOGLE_SIGNUP: 'true',
  ENABLE_GITHUB_SIGNUP: 'true',
  ENABLE_MICROSOFT_SIGNUP: 'true',
  ENABLE_BANNER_STATUS: 'false',
  CONNECTOR_BALLERINA_VERSION: '2201.3.1',
  SAMPLE_BALLERINA_VERSION: '2201.3.1',
  FEATURE_SHOW_DEV_PORTAL_CUSTOM_DOMAIN:
    'true',
  CUSTOM_DOMAINS_CNAME_RECORD_US: 'customdns.e1-us-east-azure.choreoapis.dev',
  CUSTOM_DOMAINS_CNAME_RECORD_EU: 'customdns.e1-eu-north-azure.choreoapis.dev',
  DEV_PORTAL_CUSTOM_DOMAINS_CNAME_RECORD:
    'customdns.devportal.choreo.dev',
  AZURE_INSIGHTS_KEY: '8f98bf03-9ba8-47ba-a18d-62449b92ca42',
  FEATURE_SHOW_USER_EMAIL_CONSENT: 'true',
  FEATURE_SHOW_TOS_CONSENT: 'true',
  FEATURE_ENABLE_API_VISIBILITY_SWITCH:
    'true',
  TOS_SERVICE_NAME: 'choreo',
  FEATURE_DISABLE_ANONYMOUS_LOGIN_BUTTON:
    'true',
  SENTRY_ENV: 'V2_PROD',
  SENTRY_DSN: 'https://48e24d50c8fb45d3adebfcfd8b1dd310@o350818.ingest.sentry.io/5808256',
  SENTRY_SAMPLE_RATE: '1',
  GOOGLE_CAPTCHA_SITE_KEY: '6LcS3kgbAAAAAFEdH7nY55ToDmKn22w9PdKIHSdP',
  DISABLE_GOOGLE_CAPTCHA: 'false',
  ENABLE_DEMO_ORG_FEATURE: 'true',
  DEMO_ORG_HANDLE: 'choreodemo',
  DEMO_ORG_WEB_APP_URL: 'https://horizonbank.choreoapps.dev',
  DEMO_ORG_VIEWER_SCOPES: 'apim:api_generate_key apim:api_view apim:subscribe apim:tier_view choreo:log_view_non_prod choreo:project_view environments:view_dev environments:view_prod urn:choreosystem:choreodevopsportalapi:deployment_view urn:choreosystem:componentsmanagement:component_file_view urn:choreosystem:componentsmanagement:component_logs_view urn:choreosystem:customdomainapi:custom_domain_view urn:choreosystem:organizationmanagement:theme_view',
  ENABLE_AUDIT_LOGS_VIEW: 'true',
  ENABLE_UNIFIED_LOGS_VIEW: 'true',
  SYS_API_PREFIX: '5659b6b7-1063-41ed-8e39-d91857699255-systemapis',
  FEATURE_FLAG_MAINTENANCE_BANNER: 'false',
  FEATURE_FLAG_MAINTENANCE_CUSTOM_MESSAGE:
    '',
  FEATURE_FLAG_MAINTENANCE_DATE_AND_TIME:
    '17th of January 2024 from 03:00:00 AM UTC to 04:00:00 AM UTC',
  FEATURE_FLAG_MAINTENANCE_TYPE: 'A maintenance',
  FEATURE_FLAG_MAINTENANCE_MESSAGE_SLACK_LINK:
    'https://discord.com/channels/955510916064092180/1040236871806103632/1194879309555454035',
  GIT_HUB_URL: 'https://github.com',
  GH_APP_CONFIGS: {
    GH_APP_CLIENT_ID: 'Iv1.804167a242012c66',
    PUBLIC_URL: 'https://github.com/marketplace/choreo-dev',
    GH_APP_AUTH_REDIRECTION_URL: 'https://console.choreo.dev/ghapp',
    GH_APP_INSTALL_URL: 'https://github.com/apps/choreo-dev/installations/new',
  },
  ENABLE_PROFILE_SELECTOR: '$REACT_APP_ENABLE_PROFILE_SELECTOR',
  EMAIL_LOGIN_CONFIGS: {
    ENABLE_EMAIL_LOGIN: 'true',
    POST_REGISTER_CALLBACK_URL: 'https://console.choreo.dev/login?method=basic',
    TENANT_URL_PREFIX: 'https://console.choreo.dev',
    REGISTER_MAIL_TEMPLATE_NAME: 'ChoreoLiteUserEmailConfirmation',
    ASGARDEO_SIGNUP_URL: 'https://asgardeo.io/signup',
  },
  BALLERINA_LOW_CODE_RESOURCES_VERSION:
    '20230110-1125',
  SHOW_AUTO_UNDEPLOYMENT_BANNER: 'true',
  SHOW_SCALE_TO_ZERO_BANNER: 'true',
  HIDDEN_SAMPLE_LIST: 'twilio_new_sms_to_gmail_inbox|twilio_sms_to_gsheet|ftp_new_file_to_mongodb_vfs|gcalendar_to_twilio|github_new_commit_to_google_sheet_row|gdrive_new_file_to_gsheet_rows|gmail_new_attachment_to_drive|gdrive_new_file_to_twilio_sms',
  NOTIFICATION_BANNER_INTERVAL: '300000',
  FEATURE_FLAG_CODE_EDITOR_SSO: 'true',
  DISABLE_ENTERPRISE_LOGIN: 'false',
  FEATURE_FLAG_COMPONENT_INSIGHTS: 'true',
  ENABLE_INTERNAL_API_FEATURE: 'true',
  ENABLE_PLATFORM_SERVICES_FEATURE:
    'true',
  PLATFORM_SERVICES_ENABLED_ORGANIZATIONS:
    '$REACT_APP_PLATFORM_SERVICES_ENABLED_ORGANIZATIONS',
  ENABLE_CONFIGURE_AZURE_SUBSCRIPTION_FEATURE:
    'true',
  CHOREO_SAAS_OFFER_URL: '',
  ENABLE_GRAPHQL_FEATURE: 'true',
  USER_ENABLED_FEATURE_PREVIEW_LIST:
    'Web Application Creation',
  PROJECT_DP_REGIONS: 'US,EU',
  ENABLE_AUTO_DEPLOY_BY_DEFAULT: 'true',
  ENABLE_CONFIG_INIT_ON_COMP_CREATION:
    'true',
  ENABLE_IPAAS_FEATURE: 'true',
  ENABLE_DEFAULT_ORG_CREATION: 'true',
  ENABLE_RESILIENCY_FEATURE: 'true',
  ENABLE_CDP_RESILIENCY_FEATURE: 'true',
  ASGARDEO_KEY_MANAGER_BASE_URL: 'https://api.asgardeo.io/t/',
  ENABLE_ASGARDEO_KEY_MANAGER_SWITCH:
    'true',
  ENABLE_EXTERNAL_CI_FEATURE: 'true',
  ENABLE_HELM_MARKETPLACE: '$REACT_APP_ENABLE_HELM_MARKETPLACE',
  ENABLE_KAFKA_AS_A_SERVICE: 'false',
  ENABLE_GEN_AI_SERVICES: 'true',
  OPEN_AI_TEMPLATE_ID: '1a1d9a9b-334f-4f2a-aafe-bbf1ff753aed',
  MISTRAL_AI_TEMPLATE_ID: '1a329930-ebee-4eb4-bdb6-bec868e1dd9b',
  ANTROPIC_AI_TEMPLATE_ID: '28882ffb-b4ca-4279-af94-d94141418d3d',
  AZURE_OPEN_AI_TEMPLATE_ID: '2ee3d8af-72e2-44ee-ab35-1d09d552e0eb',
  ENABLE_BYO_CLOUD_INFRASTRUCTURE: 'true',
  MAX_NO_OF_ORG_ENVS_ALLOWED: '5',
  // RBAC Permissions
  ROLE_MAPPING_MANAGE: 'urn:choreosystem:usermanagement:role_mapping_manage',
  ROLE_MAPPING_VIEW: 'urn:choreosystem:usermanagement:role_mapping_view',
  ROLE_MAPPING_CREATE: 'urn:choreosystem:usermanagement:role_mapping_create',
  ROLE_MAPPING_UPDATE: 'urn:choreosystem:usermanagement:role_mapping_update',
  ROLE_MAPPING_DELETE: 'urn:choreosystem:usermanagement:role_mapping_delete',
  ROLE_VIEW: 'urn:choreosystem:usermanagement:role_view',
  ROLE_CREATE: 'urn:choreosystem:usermanagement:role_create',
  ROLE_UPDATE: 'urn:choreosystem:usermanagement:role_update',
  ROLE_DELETE: 'urn:choreosystem:usermanagement:role_delete',
  ROLE_MANAGE: 'urn:choreosystem:usermanagement:role_manage',
  USER_VIEW: 'urn:choreosystem:usermanagement:user_view',
  USER_DELETE: 'urn:choreosystem:usermanagement:user_delete',
  USER_UPDATE: 'urn:choreosystem:usermanagement:user_update',
  PERMISSION_VIEW: 'urn:choreosystem:usermanagement:permission_view',
  USER_MANAGE: 'urn:choreosystem:usermanagement:user_manage',
  INVITATION_MANAGE: 'urn:choreosystem:usermanagement:invitation_manage',
  INVITATION_VIEW: 'urn:choreosystem:usermanagement:invitation_view',
  INVITATION_SEND: 'urn:choreosystem:usermanagement:invitation_send',
  INVITATION_DELETE: 'urn:choreosystem:usermanagement:invitation_delete',
  COMPONENT_TRIGGER: 'urn:choreosystem:componentsmanagement:component_trigger',
  COMPONENT_CREATE: 'urn:choreosystem:componentsmanagement:component_create',
  COMPONENT_CONFIG_VIEW: 'urn:choreosystem:componentsmanagement:component_config_view',
  COMPONENT_LOGS_VIEW: 'urn:choreosystem:componentsmanagement:component_logs_view',
  COMPONENT_INIT_VIEW: 'urn:choreosystem:componentsmanagement:component_init_view',
  COMPONENT_FILE_VIEW: 'urn:choreosystem:componentsmanagement:component_file_view',
  COMPONENT_MANAGE: 'urn:choreosystem:componentsmanagement:component_manage',
  GLOBAL_CONFIG_VIEW: 'urn:choreosystem:configmanagement:global_config_view',
  GLOBAL_CONFIG_UPDATE: 'urn:choreosystem:configmanagement:global_config_update',
  GLOBAL_CONFIG_MANAGE: 'urn:choreosystem:configmanagement:global_config_manage',
  GLOBAL_CONFIG_DELETE: 'urn:choreosystem:configmanagement:global_config_delete',
  GLOBAL_CONFIG_CREATE: 'urn:choreosystem:configmanagement:global_config_create',
  CONFIG_VIEW: 'urn:choreosystem:configmanagement:config_view',
  CONFIG_MANAGE: 'urn:choreosystem:configmanagement:config_manage',
  CONFIG_DELETE: 'urn:choreosystem:configmanagement:config_delete',
  CONFIG_CREATE: 'urn:choreosystem:configmanagement:config_create',
  THEME_VIEW: 'urn:choreosystem:organizationmanagement:theme_view',
  THEME_MANAGE: 'urn:choreosystem:organizationmanagement:theme_manage',
  THEME_DELETE: 'urn:choreosystem:organizationmanagement:theme_delete',
  THEME_CREATE: 'urn:choreosystem:organizationmanagement:theme_create',
  THEME_DEPLOY: 'urn:choreosystem:organizationmanagement:theme_deploy',
  ENTERPRISE_LOGIN_CONFIG_VIEW: 'urn:choreosystem:organizationmanagement:enterprise_login_config_view',
  ENTERPRISE_LOGIN_MANAGAE: '$REACT_APP_ENTERPRISE_LOGIN_MANAGAE',
  SELF_SIGNUP_CONFIG_VIEW: 'urn:choreosystem:organizationmanagement:self_signup_config_view',
  SELF_SIGNUP_CONFIG_UPDATE: 'urn:choreosystem:organizationmanagement:self_signup_config_update',
  SELF_SIGNUP_APPROVAL_VIEW: 'urn:choreosystem:organizationmanagement:self_signup_approval_view',
  SELF_SIGNUP_APPROVAL_UPDATE: '$REACT_APP_SELF_SIGNUP_APPROVAL_UPDATE',
  SELF_SIGNUP_MANAGE: 'urn:choreosystem:organizationmanagement:self_signup_manage',
  AUDIT_LOGS_VIEW: 'urn:choreosystem:choreoauditloggingapi:audit_logs_view',
  AUDIT_LOGS_MANAGE: 'urn:choreosystem:choreoauditloggingapi:audit_logs_manage',
  ON_PREM_KEY_VIEW: 'urn:choreosystem:onpremkeymanagement:on_prem_key_view',
  ON_PREM_KEY_UPDATE: 'urn:choreosystem:onpremkeymanagement:on_prem_key_update',
  ON_PREM_KEY_MANAGE: 'urn:choreosystem:onpremkeymanagement:on_prem_key_manage',
  ON_PREM_KEY_DELETE: 'urn:choreosystem:onpremkeymanagement:on_prem_key_delete',
  ON_PREM_KEY_CREATE: 'urn:choreosystem:onpremkeymanagement:on_prem_key_create',
  CHOREO_USER_MGT_VIEW_STORE_PERMISSION:
    'choreo:project_manage',
  CHOREO_ORG_MANAGE: 'urn:choreosystem:organizationapi:org_manage',
  ENV_WEBAPP_SUBDOMAIN_CONFIG: 'showOnEnvTable,showOnEnvCreate',
  ENABLE_WEBAPP_SHORT_URL_CONFIG: 'true',
  ENV_WEBAPP_SHORT_URL_DOMAINS: {
    US: 'choreoapps.dev',
    EU: 'ne.choreoapps.dev',
    IND: '',
  },
  ENABLE_YAML_CUSTOMIZATION_FEATURE:
    '$REACT_APP_ENABLE_YAML_CUSTOMIZATION_FEATURE',
  ENABLE_DEPLOYMENT_TRACK_LISTING: 'true',
  ENABLE_COMPONENT_NAME_FLOW_CONSOLE:
    'true',
  ENABLE_DT_DELETE_CONSOLE: 'true',
  ENABLE_CONFIG_GROUP_MANAGEMENT: 'false',
  YAML_CUSTOMIZATION_ENABLED_TYPES:
    '$REACT_APP_YAML_CUSTOMIZATION_ENABLED_TYPES',
  PDP_DOMAIN_CUSTOMIZED_ORGS: 'd7bc81cc-675e-4506-9fbd-75570d4d5711,bf659be2-490b-450f-ab3c-15212e85c725,11737422-7078-8510-1074-820892631194,f5aad5f4-4cac-40df-b0ed-e0c3ca8ae985,aa09155e-7c66-4eba-8f39-b32862014891',
  ENABLE_CUSTOM_CI: '$REACT_APP_ENABLE_CUSTOM_CI',
  BITBUCKET_SERVER_CUSTOMER_ORGS: 'f1373e7c-c19a-4441-947d-89c0b861635a|aa09155e-7c66-4eba-8f39-b32862014891|8e95904b-ebee-452f-8c00-95994da9c821',
  INTERNAL_MARKETPLACE_API_URL: 'https://apis.choreo.dev/marketplace/0.1.0',
  CHOREO_URL_MANAGER_URL: 'https://apis.choreo.dev/url-mgt/v1.0',
  FEATURE_DISABLE_APP_DEV_PERMISSION_ENV_BINDING:
    'true',
  ENABLE_TASK_EXECUTIONS_FEATURE: 'true',
  ENABLE_BUILD_DEPLOY_PAGE_SEPARATION:
    'false',
  FEATURE_FLAG_DEV_PORTAL_IDP_CONFIG:
    '$REACT_APP_FEATURE_FLAG_DEV_PORTAL_IDP_CONFIG',
  DEPENDENCY_CONFIG_URL: 'https://apis.choreo.dev/connections/v1.0',
  COMPONENT_MGT_BASE_URL: 'https://apis.choreo.dev/component-mgt/1.0.0',
  APIM_STS_BASE_URL: 'https://apis.choreo.dev/apim-appdev/v1.0',
  CONFIG_SVC_BASE_URL: 'https://apis.choreo.dev/config-svc/v1.0',
  API_GOVERNANCE_BASE_URL: 'https://apis.choreo.dev/governance/v1.0',
  CHOREO_MANAGED_AUTH_DOC_URL: 'https://wso2.com/choreo/docs/authentication-and-authorization/secure-web-applications-with-managed-authentication/#secure-web-applications-with-managed-authentication',
  ENABLE_PROJECT_CONNECTION_CREATION_DATE:
    '$REACT_APP_ENABLE_PROJECT_CONNECTION_CREATION_DATE',
  ENABLE_COMPONENT_NOTIFICATION: 'false',
  COMPONENT_NOTIFICATION_TEXT: '',
  COMPONENT_NOTIFICATION_LINK_TEXT:
    '',
  COMPONENT_NOTIFICATION_LINK: '',
  ENABLE_CUSTOM_URL_MAPPINGS_FEATURE:
    'true',
  RUN_TASKS_WITH_PARAMETERS: 'true',
  CHOREO_SAMPLES_VERSION: 'v29',
  SERVICE_QSG_DOC_LINK: 'https://wso2.com/choreo/docs/quick-start-guides/deploy-your-first-service/',
  WEBAPP_QSG_DOC_LINK: 'https://wso2.com/choreo/docs/quick-start-guides/deploy-your-first-static-web-application/',
  SCALE_TO_ZERO_DOC: 'https://wso2.com/choreo/docs/devops-and-ci-cd/autoscale/autoscale-components-with-scale-to-zero/',
  BUILD_TIME_ENVIRONMENT_VARIABLES_DOC_LINK:
    'https://wso2.com/choreo/docs/develop-components/deploy-an-application-with-buildpacks/#configure-build-time-environment-variables',
  ENABLE_CHOREO_AUTHORIZATION: 'true',
  ENABLE_CHOREO_AUTHORIZATION_DATE:
    '2024-05-13',
  CHOREO_CONSOLE_TEST_HEADER: 'api-key',
  ENABLE_CHOREO_PROJECT_AUTHORIZATION:
    'true',
  CHOREO_MANAGED_AUTH_LOCAL_DEV_DOC_URL:
    'https://wso2.com/choreo/docs/develop-components/develop-web-applications/develop-web-applications-locally-with-managed-authentication/',
  CHOREO_RESOURCE_AUTHZ_DOC_URL: 'https://wso2.com/choreo/docs/administer/control-access-in-the-choreo-console/',
  CHOREO_MANAGED_AUTH_LOCAL_DEV_PROXY_PACKAGE:
    '@choreo/proxy',
  QUEUED_STATUS_POLLING_INTERVAL: '30',
  IN_PROGRESS_STATUS_POLLING_INTERVAL:
    '10',
  ENABLE_MARKETPLACE_INT_ROUTING_FEATURE:
    'true',
  ENABLE_MEDIATION_FORCE_BUILD_FEATURE:
    'true',
  MEDIATION_FORCE_BUILD_ENABLED_ORGANIZATIONS:
    '*',
  CONNECTIONS_ENABLED_COMPONENT_TYPES:
    'buildpackJob|byocJob|buildpackCronjob|byocCronjob|buildpackWebhook|byocWebhook|webhook|scheduledTask|manualTrigger|buildpackEventHandler|byocEventHandler|ballerinaEventHandler|buildpackTestRunner|byocTestRunner|miApiService|miCronjob|miJob|miEventHandler|miWebhook',
  ENABLE_DEFAULT_ENDPOINT_URL_FEATURE:
    'true',
  ENABLE_RUN_WITH_ARGS_FOR_BALLERINA:
    'true',
  CUSTOM_SUBSCRIPTION_POLICY_HANDLING_ORG:
    '*',
  SUBSCRIPTION_APPROVAL_ORGS: 'd2234ec1-7bf9-4938-a237-36170c9474c2,28492cd9-0eaa-4a6a-9edf-f7215537e90e',
  DOWNLOAD_LOGS_PAGE_SIZE: '5000',
  ENABLE_ENVIRONMENT_DELETION_FEATURE:
    'true',
  APPROVAL_ORGS: 'd2234ec1-7bf9-4938-a237-36170c9474c2,28492cd9-0eaa-4a6a-9edf-f7215537e90e',
  EXECUTE_PAGE_OBS_API_ENABLED_ORGS:
    '',
  GH_PROXY_ENABLED_ORGS: '',
};
